development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: genome_restaurant_development
  pool:     5


test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: genome_restaurant_test
  pool:     5
